version: "3"

services:
  ytdl-handler:
    build:
      context: ${YT_HANDLER_DIR:-.}
    image: ytdl-handler
    container_name: ytdl-handler
    environment:
      - VIDEO_DOWNLOADER_DIR=/downloader
      - VIDEO_LANDING_DIR=/landing
      - GOTIFY_APP_TOKEN
      - GOTIFY_URL
    volumes:
      - ${YT_HANDLER_HOST_VIDEO_LANDING_DIR:-./landing}:/landing
      - ${YT_HANDLER_HOST_VIDEO_DOWNLOAD_DIR:-./downloader}:/downloader
