version: "3"

services:
  ytdl-handler:
    build:
      context: .
    image: ytdl-handler:dev
    container_name: ytdl-handler-dev
    environment:
      - VIDEO_DOWNLOADER_DIR=/downloader
      - VIDEO_LANDING_DIR=/landing
      - GOTIFY_APP_TOKEN
      - GOTIFY_URL
    volumes:
      - .:/app
      - ${HOST_VIDEO_LANDING_DIR:-./landing}:/landing
      - ${HOST_VIDEO_DOWNLOAD_DIR:-./downloader}:/downloader
